[package]
name = "img_dist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
img_hash = { git = "https://github.com/archer884/img_hash", version = "3.3.1" }
